### ISSUE TITLE
Online Oyuncu ve sunucu durumu

### ISSUE THREAD

**Issue by serkandyck** [GormYa/Fivem-Launcher#1]
Merhaba bu şahane proje için teşekkürler, Online oyuncu sayısı çekilirken gördüğüm kadarı ile fivem üzerinden alıyoruz, eğer senin firewall sistemi eklenirse malesef sunucu fivem serverliste çıkamayacaktır, onun yerine sunucu durumunu ve online oyuncusunu localhost:30120/players.json dan php ile alıp launchere  gönderirsen daha mantıklı olabilir diye düşündüm, tekrar teşekkürler

**Comment by GormYa** [comment]
Benim yazdığım firewall sistemi fivem sunucularına veri aktarımını etkilemeyecek. Online kişi sayısını ise launcher veritabanına bağlayacağım. Jsondan okunması ddos saldırılarına sebebiyet verebiliyor. Sağlıklı olan php dosyalarını ayrı sunucuda tutmak ve sunucu üzerinde 80 portunu engellemek. Bildirimin için teşekkür ederim. Online kişi sayısı gösterme sistemini değiştirince, tekrar buradan bildireceğim.

**Comment by GormYa** [comment]
32d940c numaralı commit ile online sayı artık mysql'den gelmektedir.

İlgili commit:
[https://github.com/GormYa/Fivem-Launcher/commit/3f6c9dfb2a44a77cf9750e217a917273287240d8](https://github.com/GormYa/Fivem-Launcher/commit/3f6c9dfb2a44a77cf9750e217a917273287240d8)
